name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
        tags:
            - '*'
    schedule:
        - cron: 0 13 * * MON,THU

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        if: github.event_name != 'schedule'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: pcov

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Ignore security advisory for older PHP versions
              run: composer config policy.advisories.ignore-id --json '["PKSA-qv5y-crcz-9nxw", "PKSA-kbc7-dq62-pt7d", "PKSA-8zx5-v2nz-58pb", "PKSA-fbvq-z33h-r2np", "PKSA-g9zw-qxh8-pq8w", "PKSA-yd6k-t2gh-1m43", "PKSA-1tmc-rt7x-12w6", "PKSA-xx6c-6d96-db2w", "PKSA-sjvz-tbbr-vwth", "PKSA-h8hf-ytnd-5t9q", "PKSA-wwb1-81rc-pd65", "PKSA-kvv6-36cr-fkzb", "PKSA-n14z-jjjg-g8vd", "PKSA-3mcc-k66d-pydb", "PKSA-gw7n-z4yx-7xjt", "PKSA-dpx1-78wg-1kqs", "PKSA-yhcn-xrg3-68b1", "PKSA-2wrf-1xmk-1pky", "PKSA-6319-ffpf-gx66"]'

            - name: Install the dependencies
              uses: ramsey/composer-install@v3

            - name: Generate the coverage report
              run: php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=coverage --coverage-clover=clover.xml --colors=always

            - name: Upload the coverage report
              uses: codecov/codecov-action@v4
              with:
                  files: ./clover.xml
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}

    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4 # Keep running this with PHP 7, otherwise there will be PHP 8 CS fixes
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Ignore security advisory for older PHP versions
              run: composer config policy.advisories.ignore-id --json '["PKSA-qv5y-crcz-9nxw", "PKSA-kbc7-dq62-pt7d", "PKSA-8zx5-v2nz-58pb", "PKSA-fbvq-z33h-r2np", "PKSA-g9zw-qxh8-pq8w", "PKSA-yd6k-t2gh-1m43", "PKSA-1tmc-rt7x-12w6", "PKSA-xx6c-6d96-db2w", "PKSA-sjvz-tbbr-vwth", "PKSA-h8hf-ytnd-5t9q", "PKSA-wwb1-81rc-pd65", "PKSA-kvv6-36cr-fkzb", "PKSA-n14z-jjjg-g8vd", "PKSA-3mcc-k66d-pydb", "PKSA-gw7n-z4yx-7xjt", "PKSA-dpx1-78wg-1kqs", "PKSA-yhcn-xrg3-68b1", "PKSA-2wrf-1xmk-1pky", "PKSA-6319-ffpf-gx66"]'

            - name: Install the dependencies
              uses: ramsey/composer-install@v3

            - name: Install ECS
              uses: ramsey/composer-install@v3
              with:
                  working-directory: tools/ecs

            - name: Check the coding style
              run: tools/ecs/vendor/bin/ecs check src tests --no-progress-bar --ansi

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0, 8.1, 8.2, 8.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Ignore security advisory for older PHP versions
              run: composer config policy.advisories.ignore-id --json '["PKSA-qv5y-crcz-9nxw", "PKSA-kbc7-dq62-pt7d", "PKSA-8zx5-v2nz-58pb", "PKSA-fbvq-z33h-r2np", "PKSA-g9zw-qxh8-pq8w", "PKSA-yd6k-t2gh-1m43", "PKSA-1tmc-rt7x-12w6", "PKSA-xx6c-6d96-db2w", "PKSA-sjvz-tbbr-vwth", "PKSA-h8hf-ytnd-5t9q", "PKSA-wwb1-81rc-pd65", "PKSA-kvv6-36cr-fkzb", "PKSA-n14z-jjjg-g8vd", "PKSA-3mcc-k66d-pydb", "PKSA-gw7n-z4yx-7xjt", "PKSA-dpx1-78wg-1kqs", "PKSA-yhcn-xrg3-68b1", "PKSA-2wrf-1xmk-1pky", "PKSA-6319-ffpf-gx66"]'
              if: matrix.php < 8.1

            - name: Install the dependencies
              uses: ramsey/composer-install@v3

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always
